nameOverride: ""
fullnameOverride: ""

awsRolename: testrole

job:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  schedule: "* * * * *" 
  successfulJobsHistoryLimit: 3
  suspend: false
  activeDeadlineSeconds: 3600
  ttlSecondsAfterFinished: 14400
  serviceAccount:
    name: opencost
  securityContext:
    runAsUser: 1001
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    capabilities:
      drop:
      - ALL
  image:
    repository: ghcr.io/opencost/opencost-parquet-exporter
    tag: latest
    imagePullPolicy: Always
  env:
    - name: AWS_REGION
      value: us-west-2
    - name: KUBE_CLUSTER
      value: YOUR_CLUSTER_NAME_CHANGE_ME
    - name: OPENCOST_PARQUET_FILE_KEY_PREFIX
      value: cluster=$(KUBE_CLUSTER)
    - name: OPENCOST_PARQUET_S3_BUCKET
      value: YOUR_S3_BUCKET_NAME_CHANGE_ME
    - name: OPENCOST_PARQUET_S3_REGION
      value: YOUR_S3_BUCKET_REGION_NAME_CHANGE_ME
    - name: OPENCOST_PARQUET_SVC_HOSTNAME
      value: opencost.opencost.svc.cluster.local.
    - name: OPENCOST_PARQUET_SVC_PORT
      value: "9003"
  envFrom:
  resources:
    limits:
      cpu: 2
      memory: 5Gi
    requests:
      cpu: 1
      memory: 1Gi
  dnsConfig:
    options:
      - name: single-request-reopen
      - name: ndots
        value: "2"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  terminationGracePeriodSeconds: 30