replicaCount: 1

nameOverride: ""
fullnameOverride: ""



jobs:
  <job_name>: 
    concurrencyPolicy: <concurrency_policy>
    failedJobsHistoryLimit: <failed_history_limit>
    schedule: <schedule>
    successfulJobsHistoryLimit: <successful_limit>
    suspend: <true/false>
    imagePullSecrets:
    - username: fred
      password: password
      registry: docker.io
    serviceAccount:
      name: <serviceaccount_name>
    securityContext:
      runAsUser: <security_context_user>
      runAsGroup: <security_context_group>
      fsGroup: <security_context_fs_group>
    image:
      repository: <image_repo>
      tag: <image_tag>
      imagePullPolicy: <pull_policy>
    # optional env vars
    env:
    - name: ECHO_VAR
      value: "busybox"
    envFrom:
    - secretRef:
        name: secret_data
    - configMapRef:
        name: config_data
    resources:
      limits:
        cpu: <cpu_limit>
        memory: <memory_limit>
      requests:
        cpu: <cpu_request>
        memory: <memory_request>
    dnsConfig:
      options:
      - name: single-request-reopen
      - name: ndots
        value: "2"
    dnsPolicy: <dns_policy>
    restartPolicy: <restart_policy>

    
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

nodeSelector: {}

tolerations: []

affinity: {}
