apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cronjob
spec:
  schedule: {{ .Values.opencostParquetExporter.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.opencostParquetExporter.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.opencostParquetExporter.failedJobsHistoryLimit }}
  concurrencyPolicy: Forbid
  timeZone: {{ .Values.opencostParquetExporter.timeZone }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Values.serviceAccount.name }}
          restartPolicy: {{ .Values.opencostParquetExporter.restartPolicy }}
          containers:
            - name: {{ .Chart.Name }}
              image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: ["/app/.venv/bin/python3", "/app/opencost_parquet_exporter.py"]
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
