apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    iam.amazonaws.com/role: staging-opencost
  name: export-opencost
  namespace: opencost
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      name: export-opencost
    spec:
      activeDeadlineSeconds: 3600
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: staging-opencost
          name: export-opencost
        spec:
          containers:
          - env:
            - name: AWS_REGION
              value: us-west-2
            - name: KUBE_CLUSTER
              value: YOUR_CLUSTER_NAME_CHANGE_ME
            - name: OPENCOST_PARQUET_FILE_KEY_PREFIX
              value: cluster=$(KUBE_CLUSTER)
            - name: OPENCOST_PARQUET_S3_BUCKET
              value: YOUR_S3_BUCKET_NAME_CHANGE_ME
            - name: OPENCOST_PARQUET_S3_REGION
              value: YOUR_S3_BUCKET_REGION_NAME_CHANGE_ME
            - name: OPENCOST_PARQUET_SVC_HOSTNAME
              value: opencost.opencost.svc.cluster.local.
            - name: OPENCOST_PARQUET_SVC_PORT
              value: "9003"
            - name: OPENCOST_PARQUET_STORAGE_BACKEND
              value: "[aws, azure]"
            image: ghcr.io/opencost/opencost-parquet-exporter:latest
            imagePullPolicy: Always
            name: export-opencost
            resources:
              limits:
                cpu: "2"
                memory: 10Gi
              requests:
                cpu: "1"
                memory: 2Gi
            securityContext:
              capabilities:
                drop:
                - ALL
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 1000
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            command: ["/app/.venv/bin/python3"] # Update this is if the ENTRYPOINT changes
          dnsConfig:
            options:
            - name: single-request-reopen
            - name: ndots
              value: "2"
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          securityContext: {}
          serviceAccount: K8S_SERVICE_ACCOUNT_CHANGE_ME
          serviceAccountName: K8S_SERVICE_ACCOUNT_NAME_CHANGE_ME
          terminationGracePeriodSeconds: 30
      ttlSecondsAfterFinished: 14400
  schedule: 0 6 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
