apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "parquet-exporter.name" $ }}
  annotations:
{{- include "parquet-exporter.annotations" $ | indent 4 }}
  labels:
{{ include "parquet-exporter.labels" . | indent 4 }}
spec:
  concurrencyPolicy: {{ .Values.job.concurrencyPolicy | quote}}
  failedJobsHistoryLimit: {{ .Values.job.failedJobsHistoryLimit }}
  schedule: {{ .Values.job.schedule | quote}}
  successfulJobsHistoryLimit: {{ .Values.job.successfulJobsHistoryLimit }}
  suspend: {{ .Values.job.suspend }}
  jobTemplate:
    metadata:
      name: {{ include "parquet-exporter.name" $ }}
    spec:
      activeDeadlineSeconds: {{ .Values.job.activeDeadlineSeconds }}
      ttlSecondsAfterFinished: {{ .Values.job.activeDeadlineSeconds }}
      template:
        metadata:
          annotations:
            {{- include "parquet-exporter.annotations" $ | indent 12 }}
          labels:
{{ include "parquet-exporter.labels" . | indent 12 }}
          name: {{ include "parquet-exporter.name" $ }}
        spec:
          {{- if .Values.job.imagePullSecrets }}
          {{- with .Values.job.imagePullSecrets }} 
          imagePullSecrets:
{{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if and (hasKey .Values.job "serviceAccount") (hasKey .Values.job.serviceAccount "name") }}
          serviceAccountName: {{ .Values.job.serviceAccount.name }}
          {{- end }}
          {{- if hasKey .Values.job "securityContext" }}
          {{- with .Values.job.securityContext }} 
          securityContext:
{{- toYaml . | nindent 12 }}
          {{- end }}
          {{- else}}
          securityContext: {}
          {{- end }}
          containers:
            - image: {{ .Values.job.image.repository }}:{{ .Values.job.image.tag }}
              imagePullPolicy: {{ .Values.job.image.imagePullPolicy }}
              name: {{ include "parquet-exporter.name" $ }} 
              {{- with .Values.job.resources }}
              resources:
{{ toYaml . | indent 16 }}
              {{- end }}
              {{- with .Values.job.env }}
              env:
{{ toYaml . | indent 16 }}
              {{- end }}
              {{- with .Values.job.envFrom }}
              envFrom:
{{ toYaml . | indent 16 }}
              {{- end }}    
          {{- with .Values.job.dnsConfig }}
          dnsConfig:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- if .Values.job.securityContext.runAsGroup }}
          dnsPolicy: {{ .Values.job.dnsPolicy }}
          {{- end }}
          restartPolicy: {{ .Values.job.restartPolicy }}
          {{- if .Values.job.terminationGracePeriodSeconds }}
          terminationGracePeriodSeconds: {{ .Values.job.terminationGracePeriodSeconds}}
          {{- end }}